In [1]:
import requests
import pandas as pd

url = "https://steamspy.com/api.php"

params = {
    "request": "top100in2weeks"
}

response = requests.get(url, params=params, timeout=30)

print("Code HTTP :", response.status_code)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame.from_dict(data, orient="index")

    print("Nombre de jeux récupérés :", len(df))
    display(df.head())
    print("\nColonnes disponibles :")
    print(df.columns.tolist())
else:
    print("Erreur lors de la récupération :", response.text[:500])

Code HTTP : 200
Nombre de jeux récupérés : 100

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
730,730,Counter-Strike: Global Offensive,Valve,Valve,,7642084,1173003,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,1013936
1172470,1172470,Apex Legends,Respawn,Electronic Arts,,668053,326926,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,124262
578080,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",,1520457,1037487,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,314682
1623730,1623730,Palworld,Pocketpair,Pocketpair,,358266,22443,0,"50,000,000 .. 100,000,000",0,0,0,0,2099,2999,30,18028
440,440,Team Fortress 2,Valve,Valve,,1044264,117208,0,"50,000,000 .. 100,000,000",0,0,0,0,0,0,0,43819

Colonnes disponibles :
['appid', 'name', 'developer', 'publisher', 'score_rank', 'positive', 'negative', 'userscore', 'owners', 'average_forever', 'average_2weeks', 'median_forever', 'median_2weeks', 'price', 'initialprice', 'discount', 'ccu']

In [2]:
print("Dimensions du dataset :", df.shape)

display(df.head(10))

print("\nInformations sur les colonnes :")
df.info()

print("\nValeurs manquantes :")
display(df.isna().sum())

print("\nExemple de données propriétaires :")
display(df[["name", "owners", "ccu", "price"]].head(10))

Dimensions du dataset : (100, 17)

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
730,730,Counter-Strike: Global Offensive,Valve,Valve,,7642084,1173003,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,1013936
1172470,1172470,Apex Legends,Respawn,Electronic Arts,,668053,326926,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,124262
578080,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",,1520457,1037487,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,314682
1623730,1623730,Palworld,Pocketpair,Pocketpair,,358266,22443,0,"50,000,000 .. 100,000,000",0,0,0,0,2099,2999,30,18028
440,440,Team Fortress 2,Valve,Valve,,1044264,117208,0,"50,000,000 .. 100,000,000",0,0,0,0,0,0,0,43819
1938090,1938090,Call of Duty: Modern Warfare II,"Treyarch, Raven Software, Beenox, High Moon St...",Activision,,419594,294520,0,"50,000,000 .. 100,000,000",0,0,0,0,3849,6999,45,67419
1063730,1063730,New World: Aeternum,Amazon Games,Amazon Games,,196798,90080,0,"50,000,000 .. 100,000,000",0,0,0,0,5999,5999,0,5583
2358720,2358720,Black Myth: Wukong,Game Science,Game Science,,1111720,38378,0,"50,000,000 .. 100,000,000",0,0,0,0,5999,5999,0,15004
271590,271590,Grand Theft Auto V Legacy,Rockstar North,Rockstar Games,,1739980,250576,0,"50,000,000 .. 100,000,000",0,0,0,0,0,0,0,67851
550,550,Left 4 Dead 2,Valve,Valve,,940221,23762,0,"50,000,000 .. 100,000,000",0,0,0,0,999,999,0,25122

Informations sur les colonnes :
<class 'pandas.DataFrame'>
Index: 100 entries, 730 to 1811260
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   appid            100 non-null    int64
 1   name             100 non-null    str
 2   developer        100 non-null    str
 3   publisher        100 non-null    str
 4   score_rank       100 non-null    str
 5   positive         100 non-null    int64
 6   negative         100 non-null    int64
 7   userscore        100 non-null    int64
 8   owners           100 non-null    str
 9   average_forever  100 non-null    int64
 10  average_2weeks   100 non-null    int64
 11  median_forever   100 non-null    int64
 12  median_2weeks    100 non-null    int64
 13  price            100 non-null    str
 14  initialprice     100 non-null    str
 15  discount         100 non-null    str
 16  ccu              100 non-null    int64
dtypes: int64(9), str(8)
memory usage: 22.4 KB

Valeurs manquantes :

appid              0
name               0
developer          0
publisher          0
score_rank         0
positive           0
negative           0
userscore          0
owners             0
average_forever    0
average_2weeks     0
median_forever     0
median_2weeks      0
price              0
initialprice       0
discount           0
ccu                0
dtype: int64

Exemple de données propriétaires :

,name,owners,ccu,price
730,Counter-Strike: Global Offensive,"100,000,000 .. 200,000,000",1013936,0
1172470,Apex Legends,"100,000,000 .. 200,000,000",124262,0
578080,PUBG: BATTLEGROUNDS,"100,000,000 .. 200,000,000",314682,0
1623730,Palworld,"50,000,000 .. 100,000,000",18028,2099
440,Team Fortress 2,"50,000,000 .. 100,000,000",43819,0
1938090,Call of Duty: Modern Warfare II,"50,000,000 .. 100,000,000",67419,3849
1063730,New World: Aeternum,"50,000,000 .. 100,000,000",5583,5999
2358720,Black Myth: Wukong,"50,000,000 .. 100,000,000",15004,5999
271590,Grand Theft Auto V Legacy,"50,000,000 .. 100,000,000",67851,0
550,Left 4 Dead 2,"50,000,000 .. 100,000,000",25122,999

In [3]:
import time

appid = int(df.iloc[0]["appid"])

url_detail = "https://steamspy.com/api.php"
params_detail = {
    "request": "appdetails",
    "appid": appid
}

response_detail = requests.get(
    url_detail,
    params=params_detail,
    timeout=30
)

print("Code HTTP :", response_detail.status_code)

if response_detail.status_code == 200:
    details = response_detail.json()
    print("Jeu :", details.get("name"))
    print("Genres :", details.get("genre"))
    print("Clés disponibles :", list(details.keys()))
else:
    print("Erreur :", response_detail.text[:500])

Code HTTP : 200
Jeu : Counter-Strike: Global Offensive
Genres : Action, Free To Play
Clés disponibles : ['appid', 'name', 'developer', 'publisher', 'score_rank', 'positive', 'negative', 'userscore', 'owners', 'average_forever', 'average_2weeks', 'median_forever', 'median_2weeks', 'price', 'initialprice', 'discount', 'ccu', 'languages', 'genre', 'tags']

In [4]:

import requests
import pandas as pd
import time

BASE_URL = "https://steamspy.com/api.php"

# Classements à récupérer
classements = [
    "top100in2weeks",
    "top100forever",
    "top100owned"
]

catalogues = []

for classement in classements:
    print(f"Récupération : {classement}")

    try:
        response = requests.get(
            BASE_URL,
            params={"request": classement},
            timeout=30
        )
        response.raise_for_status()

        donnees = response.json()
        catalogue = pd.DataFrame.from_dict(
            donnees, orient="index"
        )

        if not catalogue.empty:
            catalogue["appid"] = pd.to_numeric(
                catalogue["appid"], errors="coerce"
            )
            catalogue = catalogue.dropna(subset=["appid"])
            catalogue["appid"] = catalogue["appid"].astype(int)
            catalogue["source_classement"] = classement
            catalogues.append(catalogue)

            print(f"  {len(catalogue)} jeux récupérés")
        else:
            print("  Aucun jeu retourné")

    except (requests.RequestException, ValueError) as erreur:
        print(f"  Erreur : {erreur}")

    # Pause pour éviter d'enchaîner les requêtes
    time.sleep(65)

if catalogues:
    jeux = pd.concat(catalogues, ignore_index=True)

    # Fusion des doublons en conservant une ligne par jeu
    jeux = jeux.drop_duplicates(subset="appid", keep="first")

    print("\nNombre de jeux uniques :", len(jeux))
    print("\nColonnes disponibles :")
    print(jeux.columns.tolist())

    display(jeux.head(10))
else:
    print("Aucun catalogue récupéré.")

Récupération : top100in2weeks
  100 jeux récupérés
Récupération : top100forever
  100 jeux récupérés
Récupération : top100owned
  100 jeux récupérés

Nombre de jeux uniques : 100

Colonnes disponibles :
['appid', 'name', 'developer', 'publisher', 'score_rank', 'positive', 'negative', 'userscore', 'owners', 'average_forever', 'average_2weeks', 'median_forever', 'median_2weeks', 'price', 'initialprice', 'discount', 'ccu', 'source_classement']

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu,source_classement
0,730,Counter-Strike: Global Offensive,Valve,Valve,,7642084,1173003,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,1013936,top100in2weeks
1,1172470,Apex Legends,Respawn,Electronic Arts,,668053,326926,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,124262,top100in2weeks
2,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",,1520457,1037487,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,314682,top100in2weeks
3,1623730,Palworld,Pocketpair,Pocketpair,,358266,22443,0,"50,000,000 .. 100,000,000",0,0,0,0,2099,2999,30,18028,top100in2weeks
4,440,Team Fortress 2,Valve,Valve,,1044264,117208,0,"50,000,000 .. 100,000,000",0,0,0,0,0,0,0,43819,top100in2weeks
5,1938090,Call of Duty: Modern Warfare II,"Treyarch, Raven Software, Beenox, High Moon St...",Activision,,419594,294520,0,"50,000,000 .. 100,000,000",0,0,0,0,3849,6999,45,67419,top100in2weeks
6,1063730,New World: Aeternum,Amazon Games,Amazon Games,,196798,90080,0,"50,000,000 .. 100,000,000",0,0,0,0,5999,5999,0,5583,top100in2weeks
7,2358720,Black Myth: Wukong,Game Science,Game Science,,1111720,38378,0,"50,000,000 .. 100,000,000",0,0,0,0,5999,5999,0,15004,top100in2weeks
8,271590,Grand Theft Auto V Legacy,Rockstar North,Rockstar Games,,1739980,250576,0,"50,000,000 .. 100,000,000",0,0,0,0,0,0,0,67851,top100in2weeks
9,550,Left 4 Dead 2,Valve,Valve,,940221,23762,0,"50,000,000 .. 100,000,000",0,0,0,0,999,999,0,25122,top100in2weeks

In [5]:
print("Nombre de jeux :", len(jeux))
print("Nombre d'identifiants uniques :", jeux["appid"].nunique())

display(
    jeux[["appid", "name", "owners", "ccu"]]
    .head(20)
)

Nombre de jeux : 100
Nombre d'identifiants uniques : 100

,appid,name,owners,ccu
0,730,Counter-Strike: Global Offensive,"100,000,000 .. 200,000,000",1013936
1,1172470,Apex Legends,"100,000,000 .. 200,000,000",124262
2,578080,PUBG: BATTLEGROUNDS,"100,000,000 .. 200,000,000",314682
3,1623730,Palworld,"50,000,000 .. 100,000,000",18028
4,440,Team Fortress 2,"50,000,000 .. 100,000,000",43819
5,1938090,Call of Duty: Modern Warfare II,"50,000,000 .. 100,000,000",67419
6,1063730,New World: Aeternum,"50,000,000 .. 100,000,000",5583
7,2358720,Black Myth: Wukong,"50,000,000 .. 100,000,000",15004
8,271590,Grand Theft Auto V Legacy,"50,000,000 .. 100,000,000",67851
9,550,Left 4 Dead 2,"50,000,000 .. 100,000,000",25122
10,304930,Unturned,"50,000,000 .. 100,000,000",10408
11,1599340,Lost Ark,"50,000,000 .. 100,000,000",17355
12,236390,War Thunder,"20,000,000 .. 50,000,000",50478
13,2246340,Monster Hunter Wilds,"20,000,000 .. 50,000,000",12494
14,553850,HELLDIVERS 2,"20,000,000 .. 50,000,000",53399
15,230410,Warframe,"20,000,000 .. 50,000,000",36195
16,1245620,ELDEN RING,"20,000,000 .. 50,000,000",29529
17,105600,Terraria,"20,000,000 .. 50,000,000",24580
18,2694490,Path of Exile 2,"20,000,000 .. 50,000,000",16727
19,431960,Wallpaper Engine,"20,000,000 .. 50,000,000",91184

In [6]:
print("Nombre de jeux uniques :", jeux["appid"].nunique())

print("\nRépartition des sources :")
print(jeux["source_classement"].value_counts())

print("\nExemples de jeux :")
display(jeux[["appid", "name", "owners", "ccu"]].head(10))

Nombre de jeux uniques : 100

Répartition des sources :
source_classement
top100in2weeks    100
Name: count, dtype: int64

Exemples de jeux :

,appid,name,owners,ccu
0,730,Counter-Strike: Global Offensive,"100,000,000 .. 200,000,000",1013936
1,1172470,Apex Legends,"100,000,000 .. 200,000,000",124262
2,578080,PUBG: BATTLEGROUNDS,"100,000,000 .. 200,000,000",314682
3,1623730,Palworld,"50,000,000 .. 100,000,000",18028
4,440,Team Fortress 2,"50,000,000 .. 100,000,000",43819
5,1938090,Call of Duty: Modern Warfare II,"50,000,000 .. 100,000,000",67419
6,1063730,New World: Aeternum,"50,000,000 .. 100,000,000",5583
7,2358720,Black Myth: Wukong,"50,000,000 .. 100,000,000",15004
8,271590,Grand Theft Auto V Legacy,"50,000,000 .. 100,000,000",67851
9,550,Left 4 Dead 2,"50,000,000 .. 100,000,000",25122

In [10]:
url = "https://steamspy.com/api.php"

params = {
    "request": "all",
    "page": 0
}

response = requests.get(url, params=params, timeout=30)

print("Code HTTP :", response.status_code)

if response.status_code == 200:
    donnees = response.json()
    catalogue = pd.DataFrame.from_dict(
        donnees, orient="index"
    )

    print("Nombre de jeux récupérés :", len(catalogue))
    print("Colonnes :", catalogue.columns.tolist())
    display(catalogue.head(10))
else:
    print("Erreur :", response.text[:500])

Code HTTP : 200
Nombre de jeux récupérés : 1000
Colonnes : ['appid', 'name', 'developer', 'publisher', 'score_rank', 'positive', 'negative', 'userscore', 'owners', 'average_forever', 'average_2weeks', 'median_forever', 'median_2weeks', 'price', 'initialprice', 'discount', 'ccu']

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
730,730,Counter-Strike: Global Offensive,Valve,Valve,,7642084,1173003,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,1013936
1172470,1172470,Apex Legends,Respawn,Electronic Arts,,668053,326926,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,124262
578080,578080,PUBG: BATTLEGROUNDS,PUBG Corporation,"KRAFTON, Inc.",,1520457,1037487,0,"100,000,000 .. 200,000,000",0,0,0,0,0,0,0,314682
1623730,1623730,Palworld,Pocketpair,Pocketpair,,358266,22443,0,"50,000,000 .. 100,000,000",0,0,0,0,2099,2999,30,18028
440,440,Team Fortress 2,Valve,Valve,,1044264,117208,0,"50,000,000 .. 100,000,000",0,0,0,0,0,0,0,43819
1938090,1938090,Call of Duty: Modern Warfare II,"Treyarch, Raven Software, Beenox, High Moon St...",Activision,,419594,294520,0,"50,000,000 .. 100,000,000",0,0,0,0,3849,6999,45,67419
1063730,1063730,New World: Aeternum,Amazon Games,Amazon Games,,196798,90080,0,"50,000,000 .. 100,000,000",0,0,0,0,5999,5999,0,5583
2358720,2358720,Black Myth: Wukong,Game Science,Game Science,,1111720,38378,0,"50,000,000 .. 100,000,000",0,0,0,0,5999,5999,0,15004
271590,271590,Grand Theft Auto V Legacy,Rockstar North,Rockstar Games,,1739980,250576,0,"50,000,000 .. 100,000,000",0,0,0,0,0,0,0,67851
550,550,Left 4 Dead 2,Valve,Valve,,940221,23762,0,"50,000,000 .. 100,000,000",0,0,0,0,999,999,0,25122

In [11]:
params = {
    "request": "all",
    "page": 1
}

response = requests.get(
    "https://steamspy.com/api.php",
    params=params,
    timeout=30
)

print("Code HTTP :", response.status_code)

if response.status_code == 200:
    donnees_page2 = response.json()
    catalogue_page2 = pd.DataFrame.from_dict(
        donnees_page2, orient="index"
    )

    print("Nombre de jeux page 2 :", len(catalogue_page2))
    print(
        "Nombre d'identifiants déjà présents dans la page 1 :",
        catalogue_page2["appid"].isin(catalogue["appid"]).sum()
    )

    display(catalogue_page2.head())
else:
    print("Erreur :", response.text[:500])

Code HTTP : 200
Nombre de jeux page 2 : 1000
Nombre d'identifiants déjà présents dans la page 1 : 0

,appid,name,developer,publisher,score_rank,positive,negative,userscore,owners,average_forever,average_2weeks,median_forever,median_2weeks,price,initialprice,discount,ccu
9450,9450,"Warhammer 40,000: Dawn of War - Soulstorm",Relic Entertainment,SEGA,,16764,847,0,"1,000,000 .. 2,000,000",0,0,0,0,0,0,0,673
490220,490220,Prismata,Lunarch Studios,Lunarch Studios,,970,217,0,"1,000,000 .. 2,000,000",0,0,0,0,0,0,0,6
1301720,1301720,Escape Room - Der kranke Kollege,Bitbeast Games,Bitbeast Games,,9872,2233,0,"1,000,000 .. 2,000,000",0,0,0,0,0,0,0,63
921060,921060,Modern Combat 5,Gameloft,Gameloft,,3130,2595,0,"1,000,000 .. 2,000,000",0,0,0,0,0,0,0,1
70000,70000,Dino D-Day,800 North and Digital Ranch,800 North and Digital Ranch,,12659,2391,0,"1,000,000 .. 2,000,000",0,0,0,0,999,999,0,3

In [12]:

# Fusion des deux pages SteamSpy
catalogue_complet = pd.concat(
    [catalogue, catalogue_page2],
    ignore_index=True
)

# Suppression des éventuels doublons
catalogue_complet = catalogue_complet.drop_duplicates(
    subset="appid"
)

print("Nombre total de jeux :", len(catalogue_complet))
print(
    "Identifiants uniques :",
    catalogue_complet["appid"].nunique()
)

display(
    catalogue_complet[
        ["appid", "name", "owners", "positive", "negative", "ccu"]
    ].head(10)
)

Nombre total de jeux : 2000
Identifiants uniques : 2000

,appid,name,owners,positive,negative,ccu
0,730,Counter-Strike: Global Offensive,"100,000,000 .. 200,000,000",7642084,1173003,1013936
1,1172470,Apex Legends,"100,000,000 .. 200,000,000",668053,326926,124262
2,578080,PUBG: BATTLEGROUNDS,"100,000,000 .. 200,000,000",1520457,1037487,314682
3,1623730,Palworld,"50,000,000 .. 100,000,000",358266,22443,18028
4,440,Team Fortress 2,"50,000,000 .. 100,000,000",1044264,117208,43819
5,1938090,Call of Duty: Modern Warfare II,"50,000,000 .. 100,000,000",419594,294520,67419
6,1063730,New World: Aeternum,"50,000,000 .. 100,000,000",196798,90080,5583
7,2358720,Black Myth: Wukong,"50,000,000 .. 100,000,000",1111720,38378,15004
8,271590,Grand Theft Auto V Legacy,"50,000,000 .. 100,000,000",1739980,250576,67851
9,550,Left 4 Dead 2,"50,000,000 .. 100,000,000",940221,23762,25122

In [13]:
print("Valeurs manquantes :")
display(catalogue_complet.isna().sum())

print("\nTypes de données :")
catalogue_complet.info()

print("\nRépartition des propriétaires estimés :")
display(catalogue_complet["owners"].value_counts().head(10))

Valeurs manquantes :

appid              0
name               0
developer          0
publisher          0
score_rank         0
positive           0
negative           0
userscore          0
owners             0
average_forever    0
average_2weeks     0
median_forever     0
median_2weeks      0
price              0
initialprice       0
discount           0
ccu                0
dtype: int64

Types de données :
<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   appid            2000 non-null   int64
 1   name             2000 non-null   str
 2   developer        2000 non-null   str
 3   publisher        2000 non-null   str
 4   score_rank       2000 non-null   str
 5   positive         2000 non-null   int64
 6   negative         2000 non-null   int64
 7   userscore        2000 non-null   int64
 8   owners           2000 non-null   str
 9   average_forever  2000 non-null   int64
 10  average_2weeks   2000 non-null   int64
 11  median_forever   2000 non-null   int64
 12  median_2weeks    2000 non-null   int64
 13  price            2000 non-null   str
 14  initialprice     2000 non-null   str
 15  discount         2000 non-null   str
 16  ccu              2000 non-null   int64
dtypes: int64(9), str(8)
memory usage: 424.3 KB

Répartition des propriétaires estimés :

owners
1,000,000 .. 2,000,000        787
500,000 .. 1,000,000          550
2,000,000 .. 5,000,000        432
5,000,000 .. 10,000,000       134
10,000,000 .. 20,000,000       53
20,000,000 .. 50,000,000       32
50,000,000 .. 100,000,000       9
100,000,000 .. 200,000,000      3
Name: count, dtype: int64

In [14]:
import time

echantillon = catalogue_complet.head(10).copy()
details_jeux = []

for _, jeu in echantillon.iterrows():
    params = {
        "request": "appdetails",
        "appid": int(jeu["appid"])
    }

    try:
        response = requests.get(
            "https://steamspy.com/api.php",
            params=params,
            timeout=30
        )
        response.raise_for_status()
        details = response.json()

        details_jeux.append({
            "appid": int(jeu["appid"]),
            "genre": details.get("genre"),
            "tags": details.get("tags")
        })

        print("OK :", jeu["name"])

    except (requests.RequestException, ValueError) as erreur:
        print("Erreur pour", jeu["name"], ":", erreur)

    time.sleep(65)

df_genres_test = pd.DataFrame(details_jeux)

display(df_genres_test)

OK : Counter-Strike: Global Offensive
OK : Apex Legends
OK : PUBG: BATTLEGROUNDS
OK : Palworld
OK : Team Fortress 2
OK : Call of Duty: Modern Warfare II
OK : New World: Aeternum
OK : Black Myth: Wukong
OK : Grand Theft Auto V Legacy
OK : Left 4 Dead 2

,appid,genre,tags
0,730,"Action, Free To Play","{'FPS': 91172, 'Shooter': 65634, 'Multiplayer'..."
1,1172470,"Action, Adventure, Free To Play","{'Free to Play': 2232, 'Battle Royale': 1511, ..."
2,578080,"Action, Adventure, Massively Multiplayer, Free...","{'Survival': 14893, 'Shooter': 12788, 'Battle ..."
3,1623730,"Action, Adventure, Indie, RPG","{'Open World': 1508, 'Survival': 1382, 'Creatu..."
4,440,"Action, Free To Play","{'Free to Play': 62968, 'Hero Shooter': 61037,..."
5,1938090,Action,"{'FPS': 2144, 'Multiplayer': 1900, 'Shooter': ..."
6,1063730,"Action, Adventure, Massively Multiplayer, RPG","{'Open World': 841, 'Massively Multiplayer': 8..."
7,2358720,"Action, Adventure, RPG","{'Mythology': 9480, 'Action RPG': 7769, 'Actio..."
8,271590,"Action, Adventure","{'Open World': 32676, 'Action': 23557, 'Multip..."
9,550,Action,"{'Zombies': 21321, 'Co-op': 11476, 'FPS': 1010..."

In [15]:
print("Nombre de jeux enrichis :", len(df_genres_test))

print("\nGenres récupérés :")
display(
    df_genres_test[["appid", "genre"]]
)

print("\nGenres manquants :")
print(df_genres_test["genre"].isna().sum())

print("\nNombre de jeux avec des tags :")
print(df_genres_test["tags"].notna().sum())

Nombre de jeux enrichis : 10

Genres récupérés :

     appid                                              genre
0      730                               Action, Free To Play
1  1172470                    Action, Adventure, Free To Play
2   578080  Action, Adventure, Massively Multiplayer, Free...
3  1623730                      Action, Adventure, Indie, RPG
4      440                               Action, Free To Play
5  1938090                                             Action
6  1063730      Action, Adventure, Massively Multiplayer, RPG
7  2358720                             Action, Adventure, RPG
8   271590                                  Action, Adventure
9      550                                             Action

Genres manquants :
0

Nombre de jeux avec des tags :
10

In [16]:
# Sélection d'un échantillon de 200 jeux
echantillon_jeux = catalogue_complet.sample(
    n=min(200, len(catalogue_complet)),
    random_state=42
).copy()

print("Nombre de jeux sélectionnés :", len(echantillon_jeux))
print("Nombre d'identifiants uniques :", echantillon_jeux["appid"].nunique())

display(
    echantillon_jeux[["appid", "name", "owners", "ccu"]].head(10)
)

Nombre de jeux sélectionnés : 200
Nombre d'identifiants uniques : 200

        appid                         name                    owners    ccu
1860   529920                   Resurgence      500,000 .. 1,000,000      0
353    686810               Hell Let Loose    2,000,000 .. 5,000,000   3380
1333   339800                     HuniePop    1,000,000 .. 2,000,000    178
905    209160         Call of Duty: Ghosts    1,000,000 .. 2,000,000    106
1289   553420                        TUNIC    1,000,000 .. 2,000,000    114
1273  1036700     My Beautiful Paper Smile    1,000,000 .. 2,000,000      0
938     34870      Sniper: Ghost Warrior 2    1,000,000 .. 2,000,000     25
1731  2239150                   Thronefall      500,000 .. 1,000,000    373
65    3164500                   Schedule I  10,000,000 .. 20,000,000  22757
1323  2221490  Tom Clancy’s The Division 2    1,000,000 .. 2,000,000   9481

In [17]:
echantillon_jeux.to_csv(
    "gamescope_echantillon.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Échantillon sauvegardé : gamescope_echantillon.csv")

Échantillon sauvegardé : gamescope_echantillon.csv

In [1]:
import pandas as pd

df = pd.read_csv("gamescope_catalogue_enrichi.csv")

print("Nombre de lignes :", len(df))
print("Nombre de colonnes :", len(df.columns))
print("\nColonnes disponibles :")
print(df.columns.tolist())

print("\nStatut de collecte :")
print(df["statut_collecte"].value_counts(dropna=False))

print("\nValeurs manquantes :")
print(df[["name", "genre", "tags"]].isna().sum())

print("\nExemple de données :")
display(df[["name", "genre", "tags"]].head(5))

Nombre de lignes : 2000
Nombre de colonnes : 20

Colonnes disponibles :
['appid', 'name', 'developer', 'publisher', 'score_rank', 'positive', 'negative', 'userscore', 'owners', 'average_forever', 'average_2weeks', 'median_forever', 'median_2weeks', 'price', 'initialprice', 'discount', 'ccu', 'genre', 'tags', 'statut_collecte']

Statut de collecte :
statut_collecte
ok    2000
Name: count, dtype: int64

Valeurs manquantes :
name     0
genre    6
tags     0
dtype: int64

Exemple de données :

,name,genre,tags
0,Counter-Strike: Global Offensive,"Action, Free To Play","{""FPS"": 91172, ""Shooter"": 65634, ""Multiplayer""..."
1,Apex Legends,"Action, Adventure, Free To Play","{""Free to Play"": 2232, ""Battle Royale"": 1511, ..."
2,PUBG: BATTLEGROUNDS,"Action, Adventure, Massively Multiplayer, Free...","{""Survival"": 14893, ""Shooter"": 12788, ""Battle ..."
3,Palworld,"Action, Adventure, Indie, RPG","{""Open World"": 1508, ""Survival"": 1382, ""Creatu..."
4,Team Fortress 2,"Action, Free To Play","{""Free to Play"": 62968, ""Hero Shooter"": 61037,..."

In [2]:
# Identifier les jeux dont le genre est manquant
genres_manquants = df[df["genre"].isna()]

display(
    genres_manquants[["appid", "name", "genre", "tags", "statut_collecte"]]
)

print("Nombre de genres manquants :", len(genres_manquants))

,appid,name,genre,tags,statut_collecte
206,241930,Middle-earth: Shadow of Mordor,NaN,"{""Open World"": 1552, ""Action"": 1441, ""Fantasy""...",ok
605,900883,The Elder Scrolls IV: Oblivion Game of the Yea...,NaN,"{""RPG"": 1540, ""Open World"": 1457, ""Fantasy"": 1...",ok
1160,250820,SteamVR,NaN,"{""VR"": 645, ""Software"": 353, ""Simulation"": 162...",ok
1174,247120,Portal 2 Sixense Perceptual Pack,NaN,"{""Adventure"": 5004, ""Free to Play"": 87, ""Actio...",ok
1477,955900,Amazing Cultivation Simulator,NaN,"{""Simulation"": 273, ""Martial Arts"": 214, ""RPG""...",ok
1852,1504980,It Takes Two Friend's Pass,NaN,"{""Online Co-Op"": 58, ""Co-op"": 56, ""Multiplayer...",ok

Nombre de genres manquants : 6

In [3]:

# Repérer les produits dont les tags suggèrent un DLC,
# un logiciel ou un outil plutôt qu'un jeu classique.

motifs_exclusion = [
    "DLC",
    "Software",
    "Utilities",
    "Video Production",
    "Audio Production",
    "Web Publishing",
    "Design & Illustration"
]

for motif in motifs_exclusion:
    masque = df["tags"].fillna("").str.contains(
        motif, case=False, regex=False
    )
    print(f"\n--- {motif} : {masque.sum()} résultats ---")
    display(df.loc[masque, ["appid", "name", "genre", "tags"]].head(10))

--- DLC : 0 résultats ---

Empty DataFrame
Columns: [appid, name, genre, tags]
Index: []

--- Software : 26 résultats ---

,appid,name,genre,tags
19,431960,Wallpaper Engine,"Casual, Indie, Animation & Modeling, Design & ...","{""Mature"": 3947, ""Utilities"": 2610, ""Anime"": 2..."
154,365670,Blender,"Animation & Modeling, Design & Illustration, V...","{""Animation & Modeling"": 754, ""Software"": 542,..."
262,1366800,Crosshair X,"Action, Adventure, Indie, Software Training, U...","{""Action"": 116, ""Indie"": 80, ""Adventure"": 72, ..."
429,629520,Soundpad,"Audio Production, Utilities","{""Utilities"": 173, ""Audio Production"": 163, ""M..."
593,993090,Lossless Scaling,Utilities,"{""Utilities"": 100, ""Software"": 69, ""Pixel Grap..."
816,1840,Source Filmmaker,"Animation & Modeling, Video Production","{""Animation & Modeling"": 772, ""Free to Play"": ..."
989,431730,Aseprite,"Animation & Modeling, Design & Illustration, G...","{""Pixel Graphics"": 246, ""Design & Illustration..."
1016,1447430,小黑盒加速器,"Software Training, Web Publishing, Game Develo...","{""Web Publishing"": 26, ""Game Development"": 24,..."
1032,400040,ShareX,"Free To Play, Audio Production, Design & Illus...","{""Photo Editing"": 115, ""Utilities"": 110, ""Free..."
1121,223850,3DMark,Utilities,"{""Benchmark"": 321, ""Utilities"": 207, ""Software..."

--- Utilities : 28 résultats ---

,appid,name,genre,tags
19,431960,Wallpaper Engine,"Casual, Indie, Animation & Modeling, Design & ...","{""Mature"": 3947, ""Utilities"": 2610, ""Anime"": 2..."
154,365670,Blender,"Animation & Modeling, Design & Illustration, V...","{""Animation & Modeling"": 754, ""Software"": 542,..."
262,1366800,Crosshair X,"Action, Adventure, Indie, Software Training, U...","{""Action"": 116, ""Indie"": 80, ""Adventure"": 72, ..."
429,629520,Soundpad,"Audio Production, Utilities","{""Utilities"": 173, ""Audio Production"": 163, ""M..."
593,993090,Lossless Scaling,Utilities,"{""Utilities"": 100, ""Software"": 69, ""Pixel Grap..."
596,3132990,Black Myth: Wukong Benchmark Tool,"Free To Play, Utilities","{""Free to Play"": 185, ""Utilities"": 138, ""Bench..."
989,431730,Aseprite,"Animation & Modeling, Design & Illustration, G...","{""Pixel Graphics"": 246, ""Design & Illustration..."
1016,1447430,小黑盒加速器,"Software Training, Web Publishing, Game Develo...","{""Web Publishing"": 26, ""Game Development"": 24,..."
1032,400040,ShareX,"Free To Play, Audio Production, Design & Illus...","{""Photo Editing"": 115, ""Utilities"": 110, ""Free..."
1121,223850,3DMark,Utilities,"{""Benchmark"": 321, ""Utilities"": 207, ""Software..."

--- Video Production : 5 résultats ---

,appid,name,genre,tags
154,365670,Blender,"Animation & Modeling, Design & Illustration, V...","{""Animation & Modeling"": 754, ""Software"": 542,..."
816,1840,Source Filmmaker,"Animation & Modeling, Video Production","{""Animation & Modeling"": 772, ""Free to Play"": ..."
1032,400040,ShareX,"Free To Play, Audio Production, Design & Illus...","{""Photo Editing"": 115, ""Utilities"": 110, ""Free..."
1205,1325860,VTube Studio,"Indie, Animation & Modeling, Video Production","{""Indie"": 261, ""Mature"": 169, ""Anime"": 131, ""A..."
1617,274920,FaceRig,"Animation & Modeling, Video Production","{""Animation & Modeling"": 290, ""Funny"": 259, ""V..."

--- Audio Production : 2 résultats ---

,appid,name,genre,tags
429,629520,Soundpad,"Audio Production, Utilities","{""Utilities"": 173, ""Audio Production"": 163, ""M..."
1032,400040,ShareX,"Free To Play, Audio Production, Design & Illus...","{""Photo Editing"": 115, ""Utilities"": 110, ""Free..."

--- Web Publishing : 2 résultats ---

,appid,name,genre,tags
1016,1447430,小黑盒加速器,"Software Training, Web Publishing, Game Develo...","{""Web Publishing"": 26, ""Game Development"": 24,..."
1032,400040,ShareX,"Free To Play, Audio Production, Design & Illus...","{""Photo Editing"": 115, ""Utilities"": 110, ""Free..."

--- Design & Illustration : 11 résultats ---

,appid,name,genre,tags
19,431960,Wallpaper Engine,"Casual, Indie, Animation & Modeling, Design & ...","{""Mature"": 3947, ""Utilities"": 2610, ""Anime"": 2..."
154,365670,Blender,"Animation & Modeling, Design & Illustration, V...","{""Animation & Modeling"": 754, ""Software"": 542,..."
262,1366800,Crosshair X,"Action, Adventure, Indie, Software Training, U...","{""Action"": 116, ""Indie"": 80, ""Adventure"": 72, ..."
264,613100,House Flipper,"Action, Adventure, Casual, Indie, Massively Mu...","{""Simulation"": 1267, ""Design & Illustration"": ..."
989,431730,Aseprite,"Animation & Modeling, Design & Illustration, G...","{""Pixel Graphics"": 246, ""Design & Illustration..."
1032,400040,ShareX,"Free To Play, Audio Production, Design & Illus...","{""Photo Editing"": 115, ""Utilities"": 110, ""Free..."
1325,648120,Pixel Sketch,"Casual, Indie, Free To Play","{""Education"": 272, ""Casual"": 265, ""Word Game"":..."
1454,1283970,YoloMouse - Cursor Changer,"Action, Indie, Free To Play, Animation & Model...","{""Utilities"": 37, ""Design & Illustration"": 33,..."
1679,2198150,Tiny Glade,"Casual, Indie, Simulation","{""Building"": 521, ""Design & Illustration"": 520..."
1712,384300,CPUCores :: Maximize Your FPS,"Design & Illustration, Utilities","{""Utilities"": 96, ""Software"": 53, ""Gaming"": 28..."

In [4]:
# Repérer les produits clairement orientés logiciel ou outils
masque_logiciels = df["genre"].fillna("").str.contains(
    "Animation & Modeling|Audio Production|Video Production|"
    "Web Publishing|Utilities|Software Training",
    case=False,
    regex=True
)

candidats_a_verifier = df.loc[
    masque_logiciels,
    ["appid", "name", "genre", "tags"]
].copy()

display(candidats_a_verifier)
print("Produits à vérifier :", len(candidats_a_verifier))

,appid,name,genre,tags
19,431960,Wallpaper Engine,"Casual, Indie, Animation & Modeling, Design & ...","{""Mature"": 3947, ""Utilities"": 2610, ""Anime"": 2..."
154,365670,Blender,"Animation & Modeling, Design & Illustration, V...","{""Animation & Modeling"": 754, ""Software"": 542,..."
262,1366800,Crosshair X,"Action, Adventure, Indie, Software Training, U...","{""Action"": 116, ""Indie"": 80, ""Adventure"": 72, ..."
429,629520,Soundpad,"Audio Production, Utilities","{""Utilities"": 173, ""Audio Production"": 163, ""M..."
593,993090,Lossless Scaling,Utilities,"{""Utilities"": 100, ""Software"": 69, ""Pixel Grap..."
596,3132990,Black Myth: Wukong Benchmark Tool,"Free To Play, Utilities","{""Free to Play"": 185, ""Utilities"": 138, ""Bench..."
816,1840,Source Filmmaker,"Animation & Modeling, Video Production","{""Animation & Modeling"": 772, ""Free to Play"": ..."
989,431730,Aseprite,"Animation & Modeling, Design & Illustration, G...","{""Pixel Graphics"": 246, ""Design & Illustration..."
1016,1447430,小黑盒加速器,"Software Training, Web Publishing, Game Develo...","{""Web Publishing"": 26, ""Game Development"": 24,..."
1032,400040,ShareX,"Free To Play, Audio Production, Design & Illus...","{""Photo Editing"": 115, ""Utilities"": 110, ""Free..."
1121,223850,3DMark,Utilities,"{""Benchmark"": 321, ""Utilities"": 207, ""Software..."
1205,1325860,VTube Studio,"Indie, Animation & Modeling, Video Production","{""Indie"": 261, ""Mature"": 169, ""Anime"": 131, ""A..."
1228,282660,Easy eSports,Utilities,"{""Utilities"": 129, ""Free to Play"": 83, ""Softwa..."
1441,689580,TurnSignal,"Software Training, Utilities","{""Utilities"": 25, ""VR"": 21, ""Software Training..."
1448,479130,ESEA,Utilities,"{""Utilities"": 156, ""Multiplayer"": 121, ""Mature..."
1454,1283970,YoloMouse - Cursor Changer,"Action, Indie, Free To Play, Animation & Model...","{""Utilities"": 37, ""Design & Illustration"": 33,..."
1458,1812620,DSX,"Action, Adventure, Indie, Simulation, Utilities","{""Simulation"": 77, ""Indie"": 75, ""Controller"": ..."
1497,323910,SteamVR Performance Test,Utilities,"{""VR"": 242, ""Benchmark"": 181, ""Software"": 173,..."
1507,1009850,OVR Advanced Settings,Utilities,"{""VR"": 84, ""Utilities"": 73, ""Software"": 45, ""I..."
1567,545110,Driver Booster 4 for Steam,Utilities,"{""Utilities"": 36}"
1617,274920,FaceRig,"Animation & Modeling, Video Production","{""Animation & Modeling"": 290, ""Funny"": 259, ""V..."
1700,268850,EVGA Precision X1,Utilities,"{""Utilities"": 81, ""Software"": 75, ""Free to Pla..."
1712,384300,CPUCores :: Maximize Your FPS,"Design & Illustration, Utilities","{""Utilities"": 96, ""Software"": 53, ""Gaming"": 28..."
1793,1068820,OVR Toolkit - Desktop Overlay,Utilities,"{""Utilities"": 68, ""VR"": 52, ""Software"": 26}"
1883,1278480,Smart Game Booster,Utilities,"{""Utilities"": 32, ""Software"": 11}"

Produits à vérifier : 25

In [5]:

# Créer une copie de travail sans les produits identifiés
# comme logiciels ou outils.

df_nettoye = df.loc[~masque_logiciels].copy()

print("Catalogue initial :", len(df))
print("Catalogue après ce premier filtre :", len(df_nettoye))
print("Produits exclus :", len(df) - len(df_nettoye))

# Vérifier les genres encore manquants
print(
    "Genres manquants restants :",
    df_nettoye["genre"].isna().sum()
)

# Exporter le catalogue de travail
df_nettoye.to_csv(
    "gamescope_catalogue_jeux.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Fichier créé : gamescope_catalogue_jeux.csv")

Catalogue initial : 2000
Catalogue après ce premier filtre : 1975
Produits exclus : 25
Genres manquants restants : 6
Fichier créé : gamescope_catalogue_jeux.csv

In [1]:
import pandas as pd

df = pd.read_csv("gamescope_catalogue_jeux.csv")

print("Nombre de lignes :", len(df))
print("Nombre de colonnes :", len(df.columns))

print("\nTypes des colonnes :")
print(df.dtypes)

print("\nValeurs manquantes :")
print(df.isna().sum())

print("\nDoublons d'identifiants :", df["appid"].duplicated().sum())

Nombre de lignes : 1975
Nombre de colonnes : 20

Types des colonnes :
appid                int64
name                   str
developer              str
publisher              str
score_rank         float64
positive             int64
negative             int64
userscore            int64
owners                 str
average_forever      int64
average_2weeks       int64
median_forever       int64
median_2weeks        int64
price                int64
initialprice         int64
discount             int64
ccu                  int64
genre                  str
tags                   str
statut_collecte        str
dtype: object

Valeurs manquantes :
appid                 0
name                  0
developer             2
publisher             5
score_rank         1975
positive              0
negative              0
userscore             0
owners                0
average_forever       0
average_2weeks        0
median_forever        0
median_2weeks         0
price                 0
initialprice          0
discount              0
ccu                   0
genre                 6
tags                  0
statut_collecte       0
dtype: int64

Doublons d'identifiants : 0

In [2]:
# Valeurs manquantes par colonne
manquants = df.isna().sum()
print("Valeurs manquantes par colonne :")
print(manquants[manquants > 0].sort_values(ascending=False))

# Vérifier les valeurs de prix
print("\nExemples de prix :")
display(
    df[["name", "price", "initialprice", "discount"]].head(10)
)

# Statistiques des prix
print("\nStatistiques des prix :")
print(df[["price", "initialprice", "discount"]].describe())

Valeurs manquantes par colonne :
score_rank    1975
genre            6
publisher        5
developer        2
dtype: int64

Exemples de prix :

                               name  price  initialprice  discount
0  Counter-Strike: Global Offensive      0             0         0
1                      Apex Legends      0             0         0
2               PUBG: BATTLEGROUNDS      0             0         0
3                          Palworld   2099          2999        30
4                   Team Fortress 2      0             0         0
5   Call of Duty: Modern Warfare II   3849          6999        45
6               New World: Aeternum   5999          5999         0
7                Black Myth: Wukong   5999          5999         0
8         Grand Theft Auto V Legacy      0             0         0
9                     Left 4 Dead 2    999           999         0

Statistiques des prix :
             price  initialprice     discount
count  1975.000000   1975.000000  1975.000000
mean   1599.885570   1865.210127    11.370633
std    1633.201519   1685.281276    26.231576
min       0.000000      0.000000     0.000000
25%      99.000000    199.000000     0.000000
50%    1099.000000   1799.000000     0.000000
75%    2499.000000   2999.000000     0.000000
max    6999.000000   9999.000000   100.000000

In [3]:
print("Exemples de propriétaires estimés :")
display(df["owners"].dropna().head(10))

print("\nValeurs de remise :")
print(sorted(df["discount"].dropna().unique()))

print("\nGenres les plus fréquents :")
print(df["genre"].value_counts().head(15))

print("\nNombre de jeux gratuits (prix nul) :")
print((df["price"] == 0).sum())

Exemples de propriétaires estimés :

0    100,000,000 .. 200,000,000
1    100,000,000 .. 200,000,000
2    100,000,000 .. 200,000,000
3     50,000,000 .. 100,000,000
4     50,000,000 .. 100,000,000
5     50,000,000 .. 100,000,000
6     50,000,000 .. 100,000,000
7     50,000,000 .. 100,000,000
8     50,000,000 .. 100,000,000
9     50,000,000 .. 100,000,000
Name: owners, dtype: str

Valeurs de remise :
[np.int64(0), np.int64(10), np.int64(20), np.int64(25), np.int64(27), np.int64(30), np.int64(33), np.int64(35), np.int64(38), np.int64(40), np.int64(45), np.int64(48), np.int64(50), np.int64(51), np.int64(55), np.int64(56), np.int64(60), np.int64(62), np.int64(63), np.int64(65), np.int64(66), np.int64(67), np.int64(69), np.int64(70), np.int64(71), np.int64(75), np.int64(77), np.int64(78), np.int64(80), np.int64(81), np.int64(82), np.int64(85), np.int64(86), np.int64(87), np.int64(89), np.int64(90), np.int64(95), np.int64(100)]

Genres les plus fréquents :
genre
Action                           238
Action, Adventure                150
Strategy                          69
Action, Adventure, Indie          67
Action, Adventure, RPG            66
Action, Indie                     58
RPG                               56
Action, RPG                       53
Action, Adventure, Indie, RPG     42
Adventure, Indie                  38
Simulation, Strategy              35
Action, Free To Play              31
Adventure                         30
Indie, Simulation, Strategy       24
Simulation                        24
Name: count, dtype: int64

Nombre de jeux gratuits (prix nul) :
460

In [4]:

# Créer des colonnes numériques utiles pour l'analyse

df["prix_euros"] = df["price"] / 100
df["prix_initial_euros"] = df["initialprice"] / 100

# Extraire les bornes de la fourchette d'owners
owners_bornes = (
    df["owners"]
    .str.replace(",", "", regex=False)
    .str.extract(r"(\d+)\s*\.\.\s*(\d+)")
)

df["owners_min"] = pd.to_numeric(
    owners_bornes[0], errors="coerce"
)
df["owners_max"] = pd.to_numeric(
    owners_bornes[1], errors="coerce"
)

# Estimation centrale, pratique pour les graphiques
df["owners_estimes"] = (
    df["owners_min"] + df["owners_max"]
) / 2

display(
    df[
        [
            "name",
            "price",
            "prix_euros",
            "owners",
            "owners_min",
            "owners_max",
            "owners_estimes",
        ]
    ].head(10)
)

,name,price,prix_euros,owners,owners_min,owners_max,owners_estimes
0,Counter-Strike: Global Offensive,0,0.00,"100,000,000 .. 200,000,000",100000000,200000000,150000000.0
1,Apex Legends,0,0.00,"100,000,000 .. 200,000,000",100000000,200000000,150000000.0
2,PUBG: BATTLEGROUNDS,0,0.00,"100,000,000 .. 200,000,000",100000000,200000000,150000000.0
3,Palworld,2099,20.99,"50,000,000 .. 100,000,000",50000000,100000000,75000000.0
4,Team Fortress 2,0,0.00,"50,000,000 .. 100,000,000",50000000,100000000,75000000.0
5,Call of Duty: Modern Warfare II,3849,38.49,"50,000,000 .. 100,000,000",50000000,100000000,75000000.0
6,New World: Aeternum,5999,59.99,"50,000,000 .. 100,000,000",50000000,100000000,75000000.0
7,Black Myth: Wukong,5999,59.99,"50,000,000 .. 100,000,000",50000000,100000000,75000000.0
8,Grand Theft Auto V Legacy,0,0.00,"50,000,000 .. 100,000,000",50000000,100000000,75000000.0
9,Left 4 Dead 2,999,9.99,"50,000,000 .. 100,000,000",50000000,100000000,75000000.0

In [7]:

# Préparer le fichier final pour l'analyse
df_final = df.copy()

# Supprimer la colonne entièrement vide
df_final = df_final.drop(columns=["score_rank"])

# Enregistrer le fichier de travail mis à jour
df_final.to_csv(
    "gamescope_catalogue_jeux.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Fichier de travail mis à jour.")
print("Nombre de lignes :", len(df_final))
print("Nombre de colonnes :", len(df_final.columns))
print("\nColonnes finales :")
print(df_final.columns.tolist())

Fichier de travail mis à jour.
Nombre de lignes : 1975
Nombre de colonnes : 24

Colonnes finales :
['appid', 'name', 'developer', 'publisher', 'positive', 'negative', 'userscore', 'owners', 'average_forever', 'average_2weeks', 'median_forever', 'median_2weeks', 'price', 'initialprice', 'discount', 'ccu', 'genre', 'tags', 'statut_collecte', 'prix_euros', 'prix_initial_euros', 'owners_min', 'owners_max', 'owners_estimes']

In [8]:
print(df_final[
    ["name", "price", "prix_euros",
     "owners_min", "owners_max", "owners_estimes"]
].head())

print("\nValeurs manquantes dans les nouvelles colonnes :")
print(df_final[
    ["prix_euros", "owners_min", "owners_max", "owners_estimes"]
].isna().sum())

                               name  price  prix_euros  owners_min  \
0  Counter-Strike: Global Offensive      0        0.00   100000000
1                      Apex Legends      0        0.00   100000000
2               PUBG: BATTLEGROUNDS      0        0.00   100000000
3                          Palworld   2099       20.99    50000000
4                   Team Fortress 2      0        0.00    50000000

   owners_max  owners_estimes
0   200000000     150000000.0
1   200000000     150000000.0
2   200000000     150000000.0
3   100000000      75000000.0
4   100000000      75000000.0

Valeurs manquantes dans les nouvelles colonnes :
prix_euros        0
owners_min        0
owners_max        0
owners_estimes    0
dtype: int64